name: hourly cron
on:
  schedule:
    - cron: "*/15 * * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Pull most recent Garmin data
        run: "curl -X POST https://garmin-report.vercel.app/api/index --header 'Authorization: Bearer ${{ secrets.API_KEY }}'"
